INSERT INTO RE_ADDRESS_PROF_TYPE_DETAILS
(
RE_APTD_TYPE_ID,
RE_APTD_TYPE_NAME,
RE_APTD_CREATION_DATE,
RE_APTD_CREATED_BY,
RE_APTD_LAST_UPDATED_DATE,
RE_APTD_LAST_UPDATED_BY
)
VALUES(
       RE_ADDRESS_PROF_TYPE_DETAILS_SEQ.NEXTVAL,
       'AADHAAR',
       SYSDATE,
       1,
       NULL,
       NULL
       );
	   
	   
INSERT INTO RE_IDENTITY_PROF_TYPE_DETAILS
(
RE_IPTD_TYPE_ID,
RE_IPTD_TYPE_NAME,
RE_IPTD_CREATION_DATE,
RE_IPTD_CREATED_BY,
RE_IPTD_LAST_UPDATED_DATE,
RE_IPTD_LAST_UPDATED_BY
)
VALUES(
       RE_IDENTITY_PROF_TYPE_DETAILS_SEQ.NEXTVAL,
       'PANCARD',
       SYSDATE,
       1,
       NULL,
       NULL
       );


INSERT INTO RE_COUNTRY_INFO
(
RE_CI_COUNTRY_ID,
RE_CI_COUNTRY_NAME,
RE_CI_CREATION_DATE,
RE_CI_CREATED_BY,
RE_CI_LAST_UPDATED_DATE,
RE_CI_LAST_UPDATED_BY
)
VALUES(
       RE_COUNTRY_INFO_SEQ.NEXTVAL,
      'INDIA',
      SYSDATE,
      1,
      NULL,
      NULL
      );



INSERT INTO RE_STATE_INFO
(
RE_SI_STATE_ID,
RE_SI_STATE_NAME,
RE_SI_CREATION_DATE,
RE_SI_CREATED_BY,
RE_SI_LAST_UPDATED_DATE,
RE_SI_LAST_UPDATED_BY,
RE_SI_COUNTRY_ID
)
VALUES(
       RE_STATE_INFO_SEQ.NEXTVAL,
      'ANDHRA PRADESH',
      SYSDATE,
      1,
      NULL,
      NULL,
      1
      );
	  
	  
INSERT INTO RE_DISTRICT_INFO
(
RE_DI_DISTRICT_ID,
RE_DI_DISTRICT_NAME,
RE_DI_CREATION_DATE,
RE_DI_CREATED_BY,
RE_DI_LAST_UPDATED_DATE,
RE_DI_LAST_UPDATED_BY,
RE_DI_STATE_ID,
RE_DI_COUNTRY_ID
)
VALUES(
       RE_DISTRICT_INFO_SEQ.NEXTVAL,
       'BAPATLA',
       SYSDATE,
       1,
       NULL,
       NULL,
       1,
       1
       );

      
	  
INSERT INTO RE_MANDAL_INFO
(
RE_MI_MANDAL_ID,
RE_MI_MANDAL_NAME,
RE_MI_CREATION_DATE,
RE_MI_CREATED_BY,
RE_MI_LAST_UPDATED_DATE,
RE_MI_LAST_UPDATED_BY,
RE_MI_DISTRICT_ID,
RE_MI_STATE_ID,
RE_MI_COUNTRY_ID
)
VALUES(
       RE_MANDAL_INFO_SEQ.NEXTVAL,
       'CHIRALA',
       SYSDATE,
       1,
       NULL,
       NULL,
       1,
       1,
       1
       );	  
	  
	  
INSERT INTO RE_VILLAGE_INFO
(
RE_VI_VILLAGE_ID,
RE_VI_VILLAGE_NAME,
RE_VI_CREATION_DATE,
RE_VI_CREATED_BY,
RE_VI_LAST_UPDATED_DATE,
RE_VI_LAST_UPDATED_BY,
RE_VI_MANDAL_ID,
RE_VI_DISTRICT_ID,
RE_VI_STATE_ID,
RE_VI_COUNTRY_ID
)
VALUES(
       RE_VILLAGE_INFO_SEQ.NEXTVAL,
       'JANDRAPET',
       SYSDATE,
       1,
       NULL,
       NULL,
       1,
       1,
       1,
       1
       );	  
	   
	   
	   
	  
	  
	  
	  
	  
	  






	   
	   
	   
	   