DECLARE
  P_MOBILE_NUMBER VARCHAR2(100) :='6303573634';
  P_SERVICE_ID NUMBER := 1;
  P_DESTINATION_MOBILE_NUMBER VARCHAR2(100) :='9876543210';
  P_AMOUNT NUMBER :=3000;
  P_WALLET_TYPE_ID NUMBER:= 1;
  P_TRANSACTION_TYPE NUMBER := 1;
  P_PASSWORD VARCHAR2(100) := 'QUICKPAY@123';
  P_TYPE NUMBER := 1;
  P_RESPONSE_TYPE NUMBER;
  P_TRANSACTION_ID NUMBER;
  P_RESPONSE_TRANSACTION_ID NUMBER;
  P_CODE NUMBER;
  P_MESSAGE VARCHAR2(200);
  P_OUT_TRANSACTION_ID NUMBER;
 
BEGIN

  SP_TRANSACTION_DETAILS(
    P_MOBILE_NUMBER,
    P_SERVICE_ID,
    P_DESTINATION_MOBILE_NUMBER,
    P_AMOUNT,
    P_WALLET_TYPE_ID,
    P_TRANSACTION_TYPE,
    P_PASSWORD,
    P_TYPE,
    P_RESPONSE_TYPE,
    P_TRANSACTION_ID,
    P_RESPONSE_TRANSACTION_ID,
    P_CODE,
    P_MESSAGE,
    P_OUT_TRANSACTION_ID
  );
 
  DBMS_OUTPUT.PUT_LINE('P_CODE: ' || P_CODE);
  DBMS_OUTPUT.PUT_LINE('P_MESSAGE: ' || P_MESSAGE);
  DBMS_OUTPUT.PUT_LINE('P_OUT_TRANSACTION_ID: ' || P_OUT_TRANSACTION_ID);
END;