DECLARE

P_MOBILE_NUMBER  VARCHAR2(100):='&MOBILE_NUMBER';
P_TYPE  NUMBER:=&TYPE;
P_INOTP NUMBER:=&OTP;
P_NEW_PASSWORD VARCHAR2(100):='&PASSWORD';
P_OTP NUMBER;
P_CODE NUMBER;
P_MESSAGE VARCHAR2(100);

BEGIN

SP_FORGET_PASSWORD(P_MOBILE_NUMBER,P_TYPE,P_INOTP,P_NEW_PASSWORD,P_OTP,P_CODE,P_MESSAGE);

DBMS_OUTPUT.PUT_LINE('OTP      : ' || P_OTP);
DBMS_OUTPUT.PUT_LINE('CODE     : ' || P_CODE);
DBMS_OUTPUT.PUT_LINE('MESSAGE  : ' || P_MESSAGE);

END;