DECLARE
P_PARENT_MOBILE_NUMBER VARCHAR2(100):='9525101677';
P_CHILD_MOBILE_NUMBER VARCHAR2(100):='6962265559';
P_AMOUNT NUMBER:=1000;
P_SERVICE_ID NUMBER:=12;
P_CODE NUMBER;
P_MESSAGE VARCHAR2(100);
BEGIN
SP_STOCK_MOVEMENT(P_PARENT_MOBILE_NUMBER,P_CHILD_MOBILE_NUMBER,P_AMOUNT,P_SERVICE_ID,P_CODE,P_MESSAGE);
DBMS_OUTPUT.PUT_LINE('Code    : ' || P_CODE);
DBMS_OUTPUT.PUT_LINE('Message : ' || P_MESSAGE);
END;