DECLARE
P_MOBILE_NUMBER VARCHAR2(100):='7952644343';
P_PASSWORD VARCHAR2(100):='QUIKPAY@123';
P_CODE NUMBER;
P_MESSAGE VARCHAR2(100);

BEGIN

SP_USER_LOGIN(
              P_MOBILE_NUMBER, 
              P_PASSWORD,
              P_CODE, 
              P_MESSAGE
              );

DBMS_OUTPUT.PUT_LINE('Code: ' || P_CODE);
DBMS_OUTPUT.PUT_LINE('Message: ' || P_MESSAGE);
END;