DECLARE
P_CUSTOMER_FIRST_NAME VARCHAR2(100):='DINESH';
P_CUSTOMER_MIDDLE_NAME VARCHAR2(100):=NULL;
P_CUSTOMER_LAST_NAME VARCHAR2(100):='B';
P_CUSTOMER_GENDER CHAR:='M';
P_CUSTOMER_DATE_OF_BIRTH DATE:=TO_DATE('08-03-2001','DD-MM-YYYY');
P_CUSTOMER_MOBILE_NUMBER VARCHAR2(100):='6283546456';
P_PARENT_CUSTOMER_ID NUMBER:=4;
P_CUSTOMER_PERMANENT_ADDRESS VARCHAR2(100):='DESAIPETA,VETAPALEM';
P_CUSTOMER_TEMPORARY_ADDRESS VARCHAR2(100):='DESAIPETA,VETAPALEM';
P_CUSTOMER_IDENTITY_PROOF_NAME VARCHAR2(100):='PANCARD';
P_CUSTOMER_IDENTITY_PROOF_NUMBER VARCHAR2(100):='DGQPD8538F';
P_CUSTOMER_ADDRESS_PROOF_NAME VARCHAR2(100):='AADHAAR';
P_CUSTOMER_ADDRESS_PROOF_NUMBER VARCHAR2(100):='456455748526';
P_COUNTRY_NAME VARCHAR2(100):='INDIA';
P_STATE_NAME VARCHAR2(100):='ANDHRA PRADESH';
P_DISTRICT_NAME VARCHAR2(100):='BAPATLA';
P_MANDAL_NAME VARCHAR2(100):='VETAPALEM';
P_VILLAGE_NAME VARCHAR2(100):='DESAIPETA';
P_PINCODE VARCHAR2(100):='523187';
P_CODE NUMBER;
P_MESSAGE VARCHAR2(100);
P_CUSTOMER_ID NUMBER;

BEGIN
SP_RE_CUSTOMER_ONBOARDING
(
P_CUSTOMER_FIRST_NAME, 
P_CUSTOMER_MIDDLE_NAME,
P_CUSTOMER_LAST_NAME,
P_CUSTOMER_GENDER,
P_CUSTOMER_DATE_OF_BIRTH,
P_CUSTOMER_MOBILE_NUMBER, 
P_PARENT_CUSTOMER_ID, 
P_CUSTOMER_PERMANENT_ADDRESS, 
P_CUSTOMER_TEMPORARY_ADDRESS, 
P_CUSTOMER_IDENTITY_PROOF_NAME, 
P_CUSTOMER_IDENTITY_PROOF_NUMBER, 
P_CUSTOMER_ADDRESS_PROOF_NAME,
P_CUSTOMER_ADDRESS_PROOF_NUMBER, 
P_COUNTRY_NAME, 
P_STATE_NAME, 
P_DISTRICT_NAME, 
P_MANDAL_NAME, 
P_VILLAGE_NAME, 
P_PINCODE, 
P_CODE,
P_MESSAGE, 
P_CUSTOMER_ID
);
DBMS_OUTPUT.PUT_LINE('CODE||: '   ||P_CODE);
DBMS_OUTPUT.PUT_LINE('MESSAGE: '  ||P_MESSAGE);
DBMS_OUTPUT.PUT_LINE('CUSTOMER ID : ' || P_CUSTOMER_ID);
END;