CREATE TABLE RE_ADDRESS_PROF_TYPE_DETAILS
(
    RE_APTD_TYPE_ID                 NUMBER,

    RE_APTD_TYPE_NAME               VARCHAR2(50)
        CONSTRAINT RE_APTD_TYPE_NAME_NN
        NOT NULL,

    RE_APTD_CREATION_DATE           DATE
        CONSTRAINT RE_APTD_CREATION_DATE_NN
        NOT NULL,

    RE_APTD_CREATED_BY              NUMBER
        CONSTRAINT RE_APTD_CREATED_BY_NN
        NOT NULL,

    RE_APTD_LAST_UPDATED_DATE       DATE,

    RE_APTD_LAST_UPDATED_BY         NUMBER,

    CONSTRAINT RE_APTD_TYPE_NAME_CHK
        CHECK (RE_APTD_TYPE_NAME = UPPER(RE_APTD_TYPE_NAME)),

    CONSTRAINT RE_APTD_TYPE_ID_PK
        PRIMARY KEY (RE_APTD_TYPE_ID)
);