CREATE TABLE RE_COUNTRY_INFO
(
    RE_CI_COUNTRY_ID                NUMBER,

    RE_CI_COUNTRY_NAME              VARCHAR2(50)
        CONSTRAINT RE_CI_COUNTRY_NAME_NN
        NOT NULL,

    RE_CI_CREATION_DATE             DATE
        CONSTRAINT RE_CI_CREATION_DATE_NN
        NOT NULL,

    RE_CI_CREATED_BY                NUMBER
        CONSTRAINT RE_CI_CREATED_BY_NN
        NOT NULL,

    RE_CI_LAST_UPDATED_DATE         DATE,

    RE_CI_LAST_UPDATED_BY           NUMBER,

    CONSTRAINT RE_CI_COUNTRY_NAME_CHK
        CHECK (RE_CI_COUNTRY_NAME = UPPER(RE_CI_COUNTRY_NAME)),

    CONSTRAINT RE_CI_COUNTRY_ID_PK
        PRIMARY KEY (RE_CI_COUNTRY_ID)
);