CREATE TABLE RE_DISTRICT_INFO
(
    RE_DI_DISTRICT_ID               NUMBER,

    RE_DI_DISTRICT_NAME             VARCHAR2(50)
        CONSTRAINT RE_DI_DISTRICT_NAME_NN
        NOT NULL,

    RE_DI_CREATION_DATE             DATE
        CONSTRAINT RE_DI_CREATION_DATE_NN
        NOT NULL,

    RE_DI_CREATED_BY                NUMBER
        CONSTRAINT RE_DI_CREATED_BY_NN
        NOT NULL,

    RE_DI_LAST_UPDATED_DATE         DATE,

    RE_DI_LAST_UPDATED_BY           NUMBER,

    RE_DI_STATE_ID                  NUMBER,

    RE_DI_COUNTRY_ID                NUMBER,

    CONSTRAINT RE_DI_DISTRICT_NAME_CHK
        CHECK (RE_DI_DISTRICT_NAME = UPPER(RE_DI_DISTRICT_NAME)),

    CONSTRAINT RE_DI_DISTRICT_ID_PK
        PRIMARY KEY (RE_DI_DISTRICT_ID),

    CONSTRAINT RE_DI_STATE_ID_FK
        FOREIGN KEY (RE_DI_STATE_ID)
        REFERENCES RE_STATE_INFO(RE_SI_STATE_ID),

    CONSTRAINT RE_DI_COUNTRY_ID_FK
        FOREIGN KEY (RE_DI_COUNTRY_ID)
        REFERENCES RE_COUNTRY_INFO(RE_CI_COUNTRY_ID)
);