CREATE TABLE RE_IDENTITY_PROF_TYPE_DETAILS
(
    RE_IPTD_TYPE_ID                 NUMBER,

    RE_IPTD_TYPE_NAME               VARCHAR2(50)
        CONSTRAINT RE_IPTD_TYPE_NAME_NN
        NOT NULL,

    RE_IPTD_CREATION_DATE           DATE
        CONSTRAINT RE_IPTD_CREATION_DATE_NN
        NOT NULL,

    RE_IPTD_CREATED_BY              NUMBER
        CONSTRAINT RE_IPTD_CREATED_BY_NN
        NOT NULL,

    RE_IPTD_LAST_UPDATED_DATE       DATE,

    RE_IPTD_LAST_UPDATED_BY         NUMBER,

    CONSTRAINT RE_IPTD_TYPE_NAME_CHK
        CHECK (RE_IPTD_TYPE_NAME = UPPER(RE_IPTD_TYPE_NAME)),

    CONSTRAINT RE_IPTD_TYPE_ID_PK
        PRIMARY KEY (RE_IPTD_TYPE_ID)
);