CREATE TABLE RE_MANDAL_INFO
(
    RE_MI_MANDAL_ID                 NUMBER,

    RE_MI_MANDAL_NAME               VARCHAR2(50)
        CONSTRAINT RE_MI_MANDAL_NAME_NN
        NOT NULL,

    RE_MI_CREATION_DATE             DATE
        CONSTRAINT RE_MI_CREATION_DATE_NN
        NOT NULL,

    RE_MI_CREATED_BY                NUMBER
        CONSTRAINT RE_MI_CREATED_BY_NN
        NOT NULL,

    RE_MI_LAST_UPDATED_DATE         DATE,

    RE_MI_LAST_UPDATED_BY           NUMBER,

    RE_MI_DISTRICT_ID               NUMBER,

    RE_MI_STATE_ID                  NUMBER,

    RE_MI_COUNTRY_ID                NUMBER,

    CONSTRAINT RE_MI_MANDAL_NAME_CHK
        CHECK (RE_MI_MANDAL_NAME = UPPER(RE_MI_MANDAL_NAME)),

    CONSTRAINT RE_MI_MANDAL_ID_PK
        PRIMARY KEY (RE_MI_MANDAL_ID),

    CONSTRAINT RE_MI_DISTRICT_ID_FK
        FOREIGN KEY (RE_MI_DISTRICT_ID)
        REFERENCES RE_DISTRICT_INFO(RE_DI_DISTRICT_ID),

    CONSTRAINT RE_MI_STATE_ID_FK
        FOREIGN KEY (RE_MI_STATE_ID)
        REFERENCES RE_STATE_INFO(RE_SI_STATE_ID),

    CONSTRAINT RE_MI_COUNTRY_ID_FK
        FOREIGN KEY (RE_MI_COUNTRY_ID)
        REFERENCES RE_COUNTRY_INFO(RE_CI_COUNTRY_ID)
);