CREATE TABLE RE_STATE_INFO
(
    RE_SI_STATE_ID                  NUMBER,

    RE_SI_STATE_NAME                VARCHAR2(50)
        CONSTRAINT RE_SI_STATE_NAME_NN
        NOT NULL,

    RE_SI_CREATION_DATE             DATE
        CONSTRAINT RE_SI_CREATION_DATE_NN
        NOT NULL,

    RE_SI_CREATED_BY                NUMBER
        CONSTRAINT RE_SI_CREATED_BY_NN
        NOT NULL,

    RE_SI_LAST_UPDATED_DATE         DATE,

    RE_SI_LAST_UPDATED_BY           NUMBER,

    RE_SI_COUNTRY_ID                NUMBER,

    CONSTRAINT RE_SI_STATE_NAME_CHK
        CHECK (RE_SI_STATE_NAME = UPPER(RE_SI_STATE_NAME)),

    CONSTRAINT RE_SI_STATE_ID_PK
        PRIMARY KEY (RE_SI_STATE_ID),

    CONSTRAINT RE_SI_COUNTRY_ID_FK
        FOREIGN KEY (RE_SI_COUNTRY_ID)
        REFERENCES RE_COUNTRY_INFO(RE_CI_COUNTRY_ID)
);