CREATE TABLE RE_SERVICE_DETAILS
(
    RE_SD_ID                          NUMBER,

    RE_SD_NAME                        VARCHAR2(50)
        CONSTRAINT RE_SD_NAME_NN
        NOT NULL,

    RE_SD_CREATION_DATE               DATE
        CONSTRAINT RE_SD_CREATION_DATE_NN
        NOT NULL,

    RE_SD_CREATED_BY                  NUMBER
        CONSTRAINT RE_SD_CREATED_BY_NN
        NOT NULL,

    RE_SD_LAST_UPDATED_DATE           DATE,

    RE_SD_LAST_UPDATED_BY             NUMBER,

    RE_SD_SPD_ID                      NUMBER,

    RE_SD_SPD_SERVICE_TYPE_ID         NUMBER
        CONSTRAINT RE_SD_SPD_SERVICE_TYPE_ID_NN
        NOT NULL,

    CONSTRAINT RE_SD_NAME_CHK
        CHECK (RE_SD_NAME = UPPER(RE_SD_NAME)),

    CONSTRAINT RE_SD_ID_PK
        PRIMARY KEY (RE_SD_ID),

    CONSTRAINT RE_SD_SPD_ID_FK
        FOREIGN KEY (RE_SD_SPD_ID)
        REFERENCES RE_SERVICE_PROVIDER_DETAILS (RE_SPD_ID),

    CONSTRAINT RE_SD_SPD_SERVICE_TYPE_ID_FK
        FOREIGN KEY (RE_SD_SPD_SERVICE_TYPE_ID)
        REFERENCES RE_TBL_SERVICE_TYPES (RE_TST_SERVICE_TYPE_ID)
);