CREATE TABLE RE_SERVICE_PROVIDER_DETAILS
(
    RE_SPD_ID                     NUMBER,

    RE_SPD_NAME                   VARCHAR2(50)
        CONSTRAINT RE_SPD_NAME_NN
        NOT NULL,

    RE_SPD_CREATION_DATE          DATE
        CONSTRAINT RE_SPD_CREATION_DATE_NN
        NOT NULL,

    RE_SPD_CREATED_BY             NUMBER
        CONSTRAINT RE_SPD_CREATED_BY_NN
        NOT NULL,

    RE_SPD_LAST_UPDATED_DATE      DATE,

    RE_SPD_LAST_UPDATED_BY        NUMBER,

    CONSTRAINT RE_SPD_NAME_CHK
        CHECK (RE_SPD_NAME = UPPER(RE_SPD_NAME)),

    CONSTRAINT RE_SPD_ID_PK
        PRIMARY KEY (RE_SPD_ID)
);