CREATE TABLE RE_TBL_SERVICE_TYPES
(
    RE_TST_SERVICE_TYPE_ID              NUMBER,

    RE_TST_SERVICE_TYPE_NAME            VARCHAR2(50)
        CONSTRAINT RE_TST_SERVICE_TYPE_NAME_NN
        NOT NULL,

    RE_TST_CREATION_DATE                DATE
        CONSTRAINT RE_TST_CREATION_DATE_NN
        NOT NULL,

    RE_TST_CREATED_BY                   NUMBER
        CONSTRAINT RE_TST_CREATED_BY_NN
        NOT NULL,

    RE_TST_LAST_UPDATED_DATE            DATE,

    RE_TST_LAST_UPDATED_BY              NUMBER,

    CONSTRAINT RE_TST_SERVICE_TYPE_NAME_CHK
        CHECK (RE_TST_SERVICE_TYPE_NAME = UPPER(RE_TST_SERVICE_TYPE_NAME)),

    CONSTRAINT RE_TST_SERVICE_TYPE_ID_PK
        PRIMARY KEY (RE_TST_SERVICE_TYPE_ID)
);