CREATE TABLE RE_TBL_PASSWORD_CHANGE_HISTORY
(
    RE_PCH_CUSTOMER_ID              NUMBER
        CONSTRAINT RE_PCH_CUSTOMER_ID_NN
        NOT NULL,

    RE_PCH_MOBILE_NUMBER            VARCHAR2(30)
        CONSTRAINT RE_PCH_MOBILE_NUMBER_NN
        NOT NULL,

    RE_PCH_OLD_PASSWORD             VARCHAR2(50)
        CONSTRAINT RE_PCH_OLD_PASSWORD_NN
        NOT NULL,

    RE_PCH_NEW_PASSWORD             VARCHAR2(50)
        CONSTRAINT RE_PCH_NEW_PASSWORD_NN
        NOT NULL,

    RE_PCH_CREATED_DATE             DATE
        CONSTRAINT RE_PCH_CREATED_DATE_NN
        NOT NULL,

    CONSTRAINT RE_PCH_CUSTOMER_ID_FK
        FOREIGN KEY (RE_PCH_CUSTOMER_ID)
        REFERENCES RE_TBL_CUSTOMER_AUTHENTICATION (RE_RTCA_CUS_ID)
);