CREATE TABLE RE_TBL_LEDGER_DETAILS
(
    RE_LD_CUSTOMER_ID                 NUMBER
        CONSTRAINT RE_LD_CUSTOMER_ID_NN
        NOT NULL,

    RE_LD_SERVICE_ID                  NUMBER
        CONSTRAINT RE_LD_SERVICE_ID_NN
        NOT NULL,

    RE_LD_WALLET_ID                   NUMBER
        CONSTRAINT RE_LD_WALLET_ID_NN
        NOT NULL,

    RE_LD_CREATION_DATE               DATE
        CONSTRAINT RE_LD_CREATION_DATE_NN
        NOT NULL,

    RE_LD_OPENING_BALANCE             NUMBER
        CONSTRAINT RE_LD_OPENING_BALANCE_NN
        NOT NULL,

    RE_LD_CLOSING_BALANCE             NUMBER
        CONSTRAINT RE_LD_CLOSING_BALANCE_NN
        NOT NULL,

    CONSTRAINT RE_LD_CUSTOMER_ID_FK
        FOREIGN KEY (RE_LD_CUSTOMER_ID)
        REFERENCES RE_TBL_CUSTOMER_AUTHENTICATION (RE_RTCA_CUS_ID),

    CONSTRAINT RE_LD_SERVICE_ID_FK
        FOREIGN KEY (RE_LD_SERVICE_ID)
        REFERENCES RE_SERVICE_DETAILS (RE_SD_ID),

    CONSTRAINT RE_LD_WALLET_ID_FK
        FOREIGN KEY (RE_LD_WALLET_ID)
        REFERENCES RE_WALLET_TYPES (RE_WT_WALLET_TYPE_ID)
);