CREATE TABLE RE_TBL_TAX
(
    RE_TT_SNO                          NUMBER
        CONSTRAINT RE_TT_SNO_PK
        PRIMARY KEY,

    RE_TT_SERVICE_ID                   NUMBER
        CONSTRAINT RE_TT_SERVICE_ID_NN
        NOT NULL,

    RE_TT_SERVICE_PROVIDER_ID          NUMBER
        CONSTRAINT RE_TT_SERVICE_PROVIDER_ID_NN
        NOT NULL,

    RE_TT_TAX_PERCENTAGE               NUMBER
        CONSTRAINT RE_TT_TAX_PERCENTAGE_NN
        NOT NULL,

    RE_TT_FROM_AMOUNT                  NUMBER
        CONSTRAINT RE_TT_FROM_AMOUNT_NN
        NOT NULL,

    RE_TT_TO_AMOUNT                    NUMBER
        CONSTRAINT RE_TT_TO_AMOUNT_NN
        NOT NULL,

    RE_TT_CREATED_DATE                 DATE
        CONSTRAINT RE_TT_CREATED_DATE_NN
        NOT NULL,

    RE_TT_LAST_UPDATED_DATE            DATE,

    CONSTRAINT RE_TT_SERVICE_ID_FK
        FOREIGN KEY (RE_TT_SERVICE_ID)
        REFERENCES RE_SERVICE_DETAILS(RE_SD_ID),

    CONSTRAINT RE_TT_SERVICE_PROVIDER_ID_FK
        FOREIGN KEY (RE_TT_SERVICE_PROVIDER_ID)
        REFERENCES RE_SERVICE_PROVIDER_DETAILS(RE_SPD_ID)
);