CREATE TABLE RE_TRANSACTION_DETAILS
(
    RE_TD_TRANSACTION_ID                  NUMBER,

    RE_TD_CUSTOMER_ID                     NUMBER
        CONSTRAINT RE_TD_CUSTOMER_ID_NN
        NOT NULL,

    RE_TD_WALLET_ID                       NUMBER
        CONSTRAINT RE_TD_WALLET_ID_NN
        NOT NULL,

    RE_TD_SP_ID                           NUMBER
        CONSTRAINT RE_TD_SP_ID_NN
        NOT NULL,

    RE_TD_SD_ID                           NUMBER
        CONSTRAINT RE_TD_SD_ID_NN
        NOT NULL,

    RE_TD_AMOUNT                          NUMBER
        CONSTRAINT RE_TD_AMOUNT_NN
        NOT NULL,

    RE_TD_CUSTOMER_MOBILE                 VARCHAR2(20)
        CONSTRAINT RE_TD_CUSTOMER_MOBILE_NN
        NOT NULL,

    RE_TD_DESTINATION_MOBILE              VARCHAR2(20),

    RE_TD_ACCOUNT_NUMBER                  VARCHAR2(50),

    RE_TD_ACTUAL_AMOUNT_DEDUCTED          NUMBER
        CONSTRAINT RE_TD_ACTUAL_AMOUNT_DEDUCTED_NN
        NOT NULL,

    RE_TD_ACTUAL_AMOUNT_CREDITED          NUMBER
        CONSTRAINT RE_TD_ACTUAL_AMOUNT_CREDITED_NN
        NOT NULL,

    RE_TD_TAX_AMOUNT                      NUMBER
        CONSTRAINT RE_TD_TAX_AMOUNT_NN
        NOT NULL,

    RE_TD_COMM_AMOUNT                     NUMBER
        CONSTRAINT RE_TD_COMM_AMOUNT_NN
        NOT NULL,

    RE_TD_TR_STATUS                       VARCHAR2(20)
        CONSTRAINT RE_TD_TR_STATUS_NN
        NOT NULL,

    RE_TD_TRANSACTION_DATE                TIMESTAMP(6)
        CONSTRAINT RE_TD_TRANSACTION_DATE_NN
        NOT NULL,

    RE_TD_TR_COMPLETED_DATE               TIMESTAMP(6)
        CONSTRAINT RE_TD_TR_COMPLETED_DATE_NN
        NOT NULL,

    RE_TD_OTHER_CHARGES                   NUMBER
        CONSTRAINT RE_TD_OTHER_CHARGES_NN
        NOT NULL,

    RE_TD_CREATION_DATE                   DATE
        CONSTRAINT RE_TD_CREATION_DATE_NN
        NOT NULL,

    RE_TD_CREATED_BY                      NUMBER
        CONSTRAINT RE_TD_CREATED_BY_NN
        NOT NULL,

    RE_TD_LAST_UPDATED_DATE               DATE,

    RE_TD_LAST_UPDATED_BY                 NUMBER,

    RE_TD_TRANSACTION_REF_ID              NUMBER,

    SERVICE_ID                            NUMBER,

    RE_TD_DESCRIPTION                     VARCHAR2(100),

    VENDOR_TRANSACTION_ID                 VARCHAR2(100),

    CONSTRAINT RE_TD_TRANSACTION_ID_PK
        PRIMARY KEY (RE_TD_TRANSACTION_ID),

    CONSTRAINT RE_TD_TR_STATUS_CHK
        CHECK (RE_TD_TR_STATUS = UPPER(RE_TD_TR_STATUS)),

    CONSTRAINT RE_TD_CUSTOMER_ID_FK
        FOREIGN KEY (RE_TD_CUSTOMER_ID)
        REFERENCES RE_TBL_CUSTOMER_AUTHENTICATION(RE_RTCA_CUS_ID),

    CONSTRAINT RE_TD_WALLET_ID_FK
        FOREIGN KEY (RE_TD_WALLET_ID)
        REFERENCES RE_WALLET_TYPES(RE_WT_WALLET_TYPE_ID),

    CONSTRAINT RE_TD_SP_ID_FK
        FOREIGN KEY (RE_TD_SP_ID)
        REFERENCES RE_SERVICE_PROVIDER_DETAILS(RE_SPD_ID),

    CONSTRAINT RE_TD_SD_ID_FK
        FOREIGN KEY (RE_TD_SD_ID)
        REFERENCES RE_SERVICE_DETAILS(RE_SD_ID)
);