CREATE TABLE RE_TBL_CUSTOMER_DETAILS
(
    RE_RTCD_CUS_ID                         NUMBER
        CONSTRAINT RE_RTCD_CUS_ID_NN
        NOT NULL,

    RE_RTCD_CUS_FIRST_NAME                 VARCHAR2(100)
        CONSTRAINT RE_RTCD_CUS_FIRST_NAME_NN
        NOT NULL,

    RE_RTCD_CUS_MIDDLE_NAME                VARCHAR2(100),

    RE_RTCD_CUS_LAST_NAME                  VARCHAR2(100)
        CONSTRAINT RE_RTCD_CUS_LAST_NAME_NN
        NOT NULL,

    RE_RTCD_CUS_GENDER                     CHAR(1)
        CONSTRAINT RE_RTCD_CUS_GENDER_NN
        NOT NULL,

    RE_RTCD_CUS_DOB                        DATE
        CONSTRAINT RE_RTCD_CUS_DOB_NN
        NOT NULL,

    RE_RTCD_CUS_PERM_ADDRESS               VARCHAR2(500)
        CONSTRAINT RE_RTCD_CUS_PERM_ADDRESS_NN
        NOT NULL,

    RE_RTCD_CUS_TEMP_ADDRESS               VARCHAR2(500),

    RE_RTCD_CUS_IDENTITY_PROF_ID           NUMBER
        CONSTRAINT RE_RTCD_CUS_IDENTITY_PROF_ID_NN
        NOT NULL,

    RE_RTCD_CUS_IDENTITY_PROF_NO           VARCHAR2(20)
        CONSTRAINT RE_RTCD_CUS_IDENTITY_PROF_NO_NN
        NOT NULL,

    RE_RTCD_CUS_ADDRESS_PROF_ID            NUMBER
        CONSTRAINT RE_RTCD_CUS_ADDRESS_PROF_ID_NN
        NOT NULL,

    RE_RTCD_CUS_ADDRESS_PROF_NO            VARCHAR2(20)
        CONSTRAINT RE_RTCD_CUS_ADDRESS_PROF_NO_NN
        NOT NULL,

    RE_RTCD_CUS_COUNTRY_ID                 NUMBER
        CONSTRAINT RE_RTCD_CUS_COUNTRY_ID_NN
        NOT NULL,

    RE_RTCD_CUS_STATE_ID                   NUMBER
        CONSTRAINT RE_RTCD_CUS_STATE_ID_NN
        NOT NULL,

    RE_RTCD_CUS_DISTRICT_ID                NUMBER
        CONSTRAINT RE_RTCD_CUS_DISTRICT_ID_NN
        NOT NULL,

    RE_RTCD_CUS_MANDAL_ID                  NUMBER
        CONSTRAINT RE_RTCD_CUS_MANDAL_ID_NN
        NOT NULL,

    RE_RTCD_CUS_VILLEGE_ID                 NUMBER,

    RE_RTCD_CUS_PINCODE                    VARCHAR2(20)
        CONSTRAINT RE_RTCD_CUS_PINCODE_NN
        NOT NULL,

    RE_RTCD_CUS_CREATION_DATE              DATE
        CONSTRAINT RE_RTCD_CUS_CREATION_DATE_NN
        NOT NULL,

    RE_RTCD_CUS_CREATED_BY                 NUMBER
        CONSTRAINT RE_RTCD_CUS_CREATED_BY_NN
        NOT NULL,

    RE_RTCD_CUS_LAST_UPDATED_DATE          DATE,

    RE_RTCD_CUS_LAST_UPDATED_BY            NUMBER,

    CONSTRAINT RE_RTCD_CUS_FIRST_NAME_CHK
        CHECK (RE_RTCD_CUS_FIRST_NAME = UPPER(RE_RTCD_CUS_FIRST_NAME)),

    CONSTRAINT RE_RTCD_CUS_LAST_NAME_CHK
        CHECK (RE_RTCD_CUS_LAST_NAME = UPPER(RE_RTCD_CUS_LAST_NAME)),

    CONSTRAINT RE_RTCD_CUS_ID_PK
        PRIMARY KEY (RE_RTCD_CUS_ID),

    CONSTRAINT RE_RTCD_CUS_ID_FK
        FOREIGN KEY (RE_RTCD_CUS_ID)
        REFERENCES RE_TBL_CUSTOMER_AUTHENTICATION(RE_RTCA_CUS_ID),

    CONSTRAINT RE_RTCD_CUS_IDENTITY_PROF_ID_FK
        FOREIGN KEY (RE_RTCD_CUS_IDENTITY_PROF_ID)
        REFERENCES RE_IDENTITY_PROF_TYPE_DETAILS(RE_IPTD_TYPE_ID),

    CONSTRAINT RE_RTCD_CUS_ADDRESS_PROF_ID_FK
        FOREIGN KEY (RE_RTCD_CUS_ADDRESS_PROF_ID)
        REFERENCES RE_ADDRESS_PROF_TYPE_DETAILS(RE_APTD_TYPE_ID),

    CONSTRAINT RE_RTCD_CUS_COUNTRY_ID_FK
        FOREIGN KEY (RE_RTCD_CUS_COUNTRY_ID)
        REFERENCES RE_COUNTRY_INFO(RE_CI_COUNTRY_ID),

    CONSTRAINT RE_RTCD_CUS_STATE_ID_FK
        FOREIGN KEY (RE_RTCD_CUS_STATE_ID)
        REFERENCES RE_STATE_INFO(RE_SI_STATE_ID),

    CONSTRAINT RE_RTCD_CUS_DISTRICT_ID_FK
        FOREIGN KEY (RE_RTCD_CUS_DISTRICT_ID)
        REFERENCES RE_DISTRICT_INFO(RE_DI_DISTRICT_ID),

    CONSTRAINT RE_RTCD_CUS_MANDAL_ID_FK
        FOREIGN KEY (RE_RTCD_CUS_MANDAL_ID)
        REFERENCES RE_MANDAL_INFO(RE_MI_MANDAL_ID),

    CONSTRAINT RE_RTCD_CUS_VILLAGE_ID_FK
        FOREIGN KEY (RE_RTCD_CUS_VILLEGE_ID)
        REFERENCES RE_VILLAGE_INFO(RE_VI_VILLAGE_ID)
);