CREATE TABLE RE_TBL_CUSTOMER_STATUS
(
    RE_RTCS_STATUS_ID                 NUMBER,

    RE_RTCS_STATUS                    VARCHAR2(10)
        CONSTRAINT RE_RTCS_STATUS_NN
        NOT NULL,

    RE_RTCS_CUS_CREATION_DATE         DATE
        CONSTRAINT RE_RTCS_CREATION_DATE_NN
        NOT NULL,

    RE_RTCS_CUS_CREATED_BY            NUMBER
        CONSTRAINT RE_RTCS_CREATED_BY_NN
        NOT NULL,

    RE_RTCS_CUS_LAST_UPDATED_DATE     DATE,

    RE_RTCS_CUS_LAST_UPDATED_BY       NUMBER,

    CONSTRAINT RE_RTCS_STATUS_CHK
        CHECK (RE_RTCS_STATUS = UPPER(RE_RTCS_STATUS)),

    CONSTRAINT RE_RTCS_STATUS_ID_PK
        PRIMARY KEY (RE_RTCS_STATUS_ID)
);