CREATE TABLE RE_TBL_CUSTOMER_AUTHENTICATION
(
    RE_RTCA_CUS_ID                     NUMBER,

    RE_RTCA_CUS_MOBILE_NUMBER          VARCHAR2(30)
        CONSTRAINT RE_RTCA_CUS_MOBILE_NUMBER_NN
        NOT NULL,

    RE_RTCA_CUS_PASSWORD               VARCHAR2(50)
        CONSTRAINT RE_RTCA_CUS_PASSWORD_NN
        NOT NULL,

    RE_RTCA_CUS_NO_OF_ATTEMPTS         NUMBER
        CONSTRAINT RE_RTCA_CUS_NO_OF_ATTEMPTS_NN
        NOT NULL,

    RE_RTCA_CUS_STATUS                 NUMBER,

    RE_RTCA_CUS_CREATION_DATE          DATE
        CONSTRAINT RE_RTCA_CUS_CREATION_DATE_NN
        NOT NULL,

    RE_RTCA_CUS_CREATED_BY             NUMBER
        CONSTRAINT RE_RTCA_CUS_CREATED_BY_NN
        NOT NULL,

    RE_RTCA_CUS_LAST_UPDATED_DATE      DATE,

    RE_RTCA_CUS_LAST_UPDATED_BY        NUMBER,

    RE_RTCA_CUS_PARENT_CUS_ID          NUMBER,

    RE_RTCA_CUS_CREDIT_LIMIT           NUMBER,

    RE_RTCA_NO_OF_TRANSACTIONS         NUMBER,

    RE_RTCA_TOTAL_SALE                 NUMBER,

    FUNCTIONEMPRESULTSET               VARCHAR2(50),

    CONSTRAINT RE_RTCA_CUS_ID_PK
        PRIMARY KEY (RE_RTCA_CUS_ID)
);