CREATE TABLE RE_TBL_CUSTOMER_OTP_DETAILS
(
    RE_COD_CUSTOMER_ID              NUMBER
        CONSTRAINT RE_COD_CUSTOMER_ID_NN
        NOT NULL,

    RE_COD_MOBILE_NUMBER            VARCHAR2(30)
        CONSTRAINT RE_COD_MOBILE_NUMBER_NN
        NOT NULL,

    RE_COD_OTP_NUMBER               NUMBER
        CONSTRAINT RE_COD_OTP_NUMBER_NN
        NOT NULL,

    RE_COD_SENT_DATE                DATE
        CONSTRAINT RE_COD_SENT_DATE_NN
        NOT NULL,

    RE_COD_STATUS                   NUMBER
        CONSTRAINT RE_COD_STATUS_NN
        NOT NULL,

    CONSTRAINT RE_COD_CUSTOMER_ID_FK
        FOREIGN KEY (RE_COD_CUSTOMER_ID)
        REFERENCES RE_TBL_CUSTOMER_AUTHENTICATION (RE_RTCA_CUS_ID)
);