CREATE TABLE RE_TBL_CUSTOMER_GRADES
(
    RE_TCG_LOWLIMIT                 NUMBER
        CONSTRAINT RE_TCG_LOWLIMIT_NN
        NOT NULL,

    RE_TCG_HILIMIT                  NUMBER
        CONSTRAINT RE_TCG_HILIMIT_NN
        NOT NULL,

    RE_TCG_GRADE                    NUMBER
        CONSTRAINT RE_TCG_GRADE_NN
        NOT NULL,

    CONSTRAINT RE_TCG_GRADE_PK
        PRIMARY KEY (RE_TCG_GRADE)
);