CREATE TABLE RE_TBL_COMMISTION
(
    RE_TC_SNO                             NUMBER
        CONSTRAINT RE_TC_SNO_PK
        PRIMARY KEY,

    RE_TC_SERVICE_ID                      NUMBER
        CONSTRAINT RE_TC_SERVICE_ID_NN
        NOT NULL,

    RE_TC_SP_ID                           NUMBER
        CONSTRAINT RE_TC_SP_ID_NN
        NOT NULL,

    RE_TC_COMMISTION_PERSENTAGE           NUMBER
        CONSTRAINT RE_TC_COMMISSION_PERCENTAGE_NN
        NOT NULL,

    RE_TC_FROM_AMOUNT                     NUMBER
        CONSTRAINT RE_TC_FROM_AMOUNT_NN
        NOT NULL,

    RE_TC_TO_AMOUNT                       NUMBER
        CONSTRAINT RE_TC_TO_AMOUNT_NN
        NOT NULL,

    RE_TC_CREATION_DATE                   DATE
        CONSTRAINT RE_TC_CREATION_DATE_NN
        NOT NULL,

    RE_TC_LAST_UPDATED_DATE               DATE,

    CONSTRAINT RE_TC_SERVICE_ID_FK
        FOREIGN KEY (RE_TC_SERVICE_ID)
        REFERENCES RE_SERVICE_DETAILS(RE_SD_ID),

    CONSTRAINT RE_TC_SP_ID_FK
        FOREIGN KEY (RE_TC_SP_ID)
        REFERENCES RE_SERVICE_PROVIDER_DETAILS(RE_SPD_ID)
);