CREATE TABLE RE_TBL_CUSTOMER_WALLET_DETAILS
(
    RE_RTCWD_CUS_ID                          NUMBER,

    RE_RTCWD_CUS_WALLET_ID                   NUMBER,

    RE_RTCWD_CUS_WALLET_AMOUNT               NUMBER
        CONSTRAINT RE_RTCWD_CUS_WALLET_AMOUNT_NN
        NOT NULL,

    RE_RTCWD_CUS_WALLET_CREATION_DATE        DATE
        CONSTRAINT RE_RTCWD_CUS_WALLET_CREATION_DATE_NN
        NOT NULL,

    RE_RTCWD_CUS_WALLET_CREATED_BY           NUMBER
        CONSTRAINT RE_RTCWD_CUS_WALLET_CREATED_BY_NN
        NOT NULL,

    RE_RTCWD_CUS_WALLET_LAST_UPDATED_DATE    DATE,

    RE_RTCWD_CUS_WALLET_LAST_UPDATED_BY      NUMBER,

    CONSTRAINT RE_RTCWD_CUS_ID_FK
        FOREIGN KEY (RE_RTCWD_CUS_ID)
        REFERENCES RE_TBL_CUSTOMER_AUTHENTICATION(RE_RTCA_CUS_ID),

    CONSTRAINT RE_RTCWD_CUS_WALLET_ID_FK
        FOREIGN KEY (RE_RTCWD_CUS_WALLET_ID)
        REFERENCES RE_WALLET_TYPES(RE_WT_WALLET_TYPE_ID)
);