CREATE TABLE RE_VILLAGE_INFO
(
    RE_VI_VILLAGE_ID                  NUMBER,

    RE_VI_VILLAGE_NAME                VARCHAR2(50)
        CONSTRAINT RE_VI_VILLAGE_NAME_NN
        NOT NULL,

    RE_VI_CREATION_DATE               DATE
        CONSTRAINT RE_VI_CREATION_DATE_NN
        NOT NULL,

    RE_VI_CREATED_BY                  NUMBER
        CONSTRAINT RE_VI_CREATED_BY_NN
        NOT NULL,

    RE_VI_LAST_UPDATED_DATE           DATE,

    RE_VI_LAST_UPDATED_BY             NUMBER,

    RE_VI_MANDAL_ID                   NUMBER
        CONSTRAINT RE_VI_MANDAL_ID_NN
        NOT NULL,

    RE_VI_DISTRICT_ID                 NUMBER
        CONSTRAINT RE_VI_DISTRICT_ID_NN
        NOT NULL,

    RE_VI_STATE_ID                    NUMBER
        CONSTRAINT RE_VI_STATE_ID_NN
        NOT NULL,

    RE_VI_COUNTRY_ID                  NUMBER
        CONSTRAINT RE_VI_COUNTRY_ID_NN
        NOT NULL,

    CONSTRAINT RE_VI_VILLAGE_NAME_CHK
        CHECK (RE_VI_VILLAGE_NAME = UPPER(RE_VI_VILLAGE_NAME)),

    CONSTRAINT RE_VI_VILLAGE_ID_PK
        PRIMARY KEY (RE_VI_VILLAGE_ID),

    CONSTRAINT RE_VI_MANDAL_ID_FK
        FOREIGN KEY (RE_VI_MANDAL_ID)
        REFERENCES RE_MANDAL_INFO(RE_MI_MANDAL_ID),

    CONSTRAINT RE_VI_DISTRICT_ID_FK
        FOREIGN KEY (RE_VI_DISTRICT_ID)
        REFERENCES RE_DISTRICT_INFO(RE_DI_DISTRICT_ID),

    CONSTRAINT RE_VI_STATE_ID_FK
        FOREIGN KEY (RE_VI_STATE_ID)
        REFERENCES RE_STATE_INFO(RE_SI_STATE_ID),

    CONSTRAINT RE_VI_COUNTRY_ID_FK
        FOREIGN KEY (RE_VI_COUNTRY_ID)
        REFERENCES RE_COUNTRY_INFO(RE_CI_COUNTRY_ID)
);