CREATE TABLE RE_WALLET_TYPES
(
    RE_WT_WALLET_TYPE_ID                 NUMBER
        CONSTRAINT RE_WT_WALLET_TYPE_ID_PK
        PRIMARY KEY,

    RE_WT_WALLET_TYPE_NAME               VARCHAR2(20)
        CONSTRAINT RE_WT_WALLET_TYPE_NAME_NN
        NOT NULL
        CONSTRAINT RE_WT_WALLET_TYPE_NAME_UNQ
        UNIQUE
        CONSTRAINT RE_WT_WALLET_TYPE_NAME_CHK
        CHECK (RE_WT_WALLET_TYPE_NAME = UPPER(RE_WT_WALLET_TYPE_NAME)),

    RE_WT_WALLET_TYPE_CREATED_DATE       DATE
        CONSTRAINT RE_WT_WALLET_TYPE_CREATED_DATE_NN
        NOT NULL,

    RE_WT_WALLET_TYPE_CREATED_BY         NUMBER
        CONSTRAINT RE_WT_WALLET_TYPE_CREATED_BY_NN
        NOT NULL,

    RE_WT_WALLET_TYPE_LAST_UPDATED_DATE  DATE,

    RE_WT_WALLET_TYPE_LAST_UPDATED_BY    NUMBER
);