CREATE OR REPLACE FUNCTION FN_GET_RE_ADDRESS_PROOF_TYPE_DETAILS
(
    P_ADDRESS_PROOF_NAME IN VARCHAR2
)
RETURN NUMBER
AS
    V_APTD_TYPE_ID RE_ADDRESS_PROF_TYPE_DETAILS.RE_APTD_TYPE_ID%TYPE;
BEGIN

    SELECT RE_APTD_TYPE_ID
      INTO V_APTD_TYPE_ID
      FROM RE_ADDRESS_PROF_TYPE_DETAILS
     WHERE RE_APTD_TYPE_NAME = UPPER(P_ADDRESS_PROOF_NAME);

    RETURN V_APTD_TYPE_ID;

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        RETURN -1;

    WHEN OTHERS THEN
        RETURN -1;

END FN_GET_RE_ADDRESS_PROOF_TYPE_DETAILS;
/