CREATE OR REPLACE FUNCTION FN_GET_RE_VILLAGE_INFO
(
    P_VILLAGE_NAME IN VARCHAR2
)
RETURN NUMBER
AS
    V_VI_VILLAGE_ID RE_VILLAGE_INFO.RE_VI_VILLAGE_ID%TYPE;
BEGIN

    SELECT RE_VI_VILLAGE_ID
      INTO V_VI_VILLAGE_ID
      FROM RE_VILLAGE_INFO
     WHERE RE_VI_VILLAGE_NAME = UPPER(P_VILLAGE_NAME);

    RETURN V_VI_VILLAGE_ID;

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        RETURN -1;

    WHEN OTHERS THEN
        RETURN -1;

END FN_GET_RE_VILLAGE_INFO;
/