CREATE OR REPLACE FUNCTION FN_GET_CUSTOMER_STATUS_ID
(
    P_CUSTOMER_STATUS IN VARCHAR2
)
RETURN NUMBER
AS
    V_CUSTOMER_STATUS_ID RE_TBL_CUSTOMER_STATUS.RE_RTCS_STATUS_ID%TYPE;
BEGIN

    SELECT RE_RTCS_STATUS_ID
      INTO V_CUSTOMER_STATUS_ID
      FROM RE_TBL_CUSTOMER_STATUS
     WHERE RE_RTCS_STATUS = UPPER(P_CUSTOMER_STATUS);

    RETURN V_CUSTOMER_STATUS_ID;

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        RETURN -1;

    WHEN OTHERS THEN
        RETURN -1;

END FN_GET_CUSTOMER_STATUS_ID;
/