CREATE OR REPLACE FUNCTION FN_GET_RE_COUNTRY_INFO
(
    P_COUNTRY_NAME IN VARCHAR2
)
RETURN NUMBER
AS
    V_CI_COUNTRY_ID RE_COUNTRY_INFO.RE_CI_COUNTRY_ID%TYPE;
BEGIN

    SELECT RE_CI_COUNTRY_ID
      INTO V_CI_COUNTRY_ID
      FROM RE_COUNTRY_INFO
     WHERE RE_CI_COUNTRY_NAME = UPPER(P_COUNTRY_NAME);

    RETURN V_CI_COUNTRY_ID;

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        RETURN -1;

    WHEN OTHERS THEN
        RETURN -1;

END FN_GET_RE_COUNTRY_INFO;
/