CREATE OR REPLACE FUNCTION FN_GET_RE_DISTRICT_INFO
(
    P_DISTRICT_NAME IN VARCHAR2
)
RETURN NUMBER
AS
    V_DI_DISTRICT_ID RE_DISTRICT_INFO.RE_DI_DISTRICT_ID%TYPE;
BEGIN

    SELECT RE_DI_DISTRICT_ID
      INTO V_DI_DISTRICT_ID
      FROM RE_DISTRICT_INFO
     WHERE RE_DI_DISTRICT_NAME = UPPER(P_DISTRICT_NAME);

    RETURN V_DI_DISTRICT_ID;

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        RETURN -1;

    WHEN OTHERS THEN
        RETURN -1;

END FN_GET_RE_DISTRICT_INFO;
/