CREATE OR REPLACE FUNCTION FN_GET_CUSTOMER_PARENT_ID
(
    P_CUSTOMER_PARENT_ID IN NUMBER
)
RETURN NUMBER
AS
    V_CUSTOMER_PARENT_ID RE_TBL_CUSTOMER_AUTHENTICATION.RE_RTCA_CUS_PARENT_CUS_ID%TYPE;
BEGIN

    -- If NULL, return NULL (no parent relationship)
    IF P_CUSTOMER_PARENT_ID IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT RE_RTCA_CUS_ID
      INTO V_CUSTOMER_PARENT_ID
      FROM RE_TBL_CUSTOMER_AUTHENTICATION
     WHERE RE_RTCA_CUS_ID = P_CUSTOMER_PARENT_ID;

    RETURN V_CUSTOMER_PARENT_ID;

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        RETURN -1;

    WHEN OTHERS THEN
        RETURN -1;

END FN_GET_CUSTOMER_PARENT_ID;
/