CREATE OR REPLACE FUNCTION FN_GET_RE_MANDAL_INFO
(
    P_MANDAL_NAME IN VARCHAR2
)
RETURN NUMBER
AS
    V_MI_MANDAL_ID RE_MANDAL_INFO.RE_MI_MANDAL_ID%TYPE;
BEGIN

    SELECT RE_MI_MANDAL_ID
      INTO V_MI_MANDAL_ID
      FROM RE_MANDAL_INFO
     WHERE RE_MI_MANDAL_NAME = UPPER(P_MANDAL_NAME);

    RETURN V_MI_MANDAL_ID;

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        RETURN -1;

    WHEN OTHERS THEN
        RETURN -1;

END FN_GET_RE_MANDAL_INFO;
/