CREATE OR REPLACE FUNCTION FN_GET_RE_IDENTITY_PROF_TYPE_DETAILS
(
    P_IPTD_TYPE_NAME IN VARCHAR2
)
RETURN NUMBER
AS
    V_IPTD_TYPE_ID RE_IDENTITY_PROF_TYPE_DETAILS.RE_IPTD_TYPE_ID%TYPE;
BEGIN

    SELECT RE_IPTD_TYPE_ID
      INTO V_IPTD_TYPE_ID
      FROM RE_IDENTITY_PROF_TYPE_DETAILS
     WHERE RE_IPTD_TYPE_NAME = UPPER(P_IPTD_TYPE_NAME);

    RETURN V_IPTD_TYPE_ID;

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        RETURN -1;

    WHEN OTHERS THEN
        RETURN -1;

END FN_GET_RE_IDENTITY_PROF_TYPE_DETAILS;
/