CREATE OR REPLACE FUNCTION FN_GET_RE_STATE_INFO
(
    P_STATE_NAME IN VARCHAR2
)
RETURN NUMBER
AS
    V_SI_STATE_ID RE_STATE_INFO.RE_SI_STATE_ID%TYPE;
BEGIN

    SELECT RE_SI_STATE_ID
      INTO V_SI_STATE_ID
      FROM RE_STATE_INFO
     WHERE RE_SI_STATE_NAME = UPPER(P_STATE_NAME);

    RETURN V_SI_STATE_ID;

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        RETURN -1;

    WHEN OTHERS THEN
        RETURN -1;

END FN_GET_RE_STATE_INFO;
/